# Generated by Django 5.1.6 on 2025-02-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gt", 0)), name="price_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock_count__gte", 0)), name="stock_count_gte_0"
            ),
        ),
    ]
